version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: zerobank-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: zerobank
      POSTGRES_PASSWORD: zerobankpassword
      POSTGRES_DB: zerobank
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
